logging:
  level:
    root: DEBUG

spring:
  application:
    name: address-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/ritesh_db
    username: root
    password: admin

server:
  port: 8083

eureka:
  cient:
    service-url:
      defaultZone: http://localhost:8761/eureka