spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ritesh-db-schema
    username: root
    password: admin

  application:
    name: address-service

server:
  port: 8083

eureka:
  cient:
    service-url:
      defaultZone: http://localhost:8761/eureka